### ISSUE TITLE
fails to display esacaped `$` when {  singleDollars: true }

### ISSUE THREAD

**Issue by beeplin** [pkra/mathjax-node-page#39]
For Mathjax in browser, if single dollars are allowed as delimiters, we can use escaped `\$` to show normal dollars. see http://docs.mathjax.org/en/latest/options/tex2jax.html?highlight=processEscapes

But currently in mathjax-node-page, if set {  singleDollars: true }, there seems no way to handle the escaped dollar, and if there is any `\$` in the text, an error is thown.

Example: 

```js
const { mjpage } = require('mathjax-node-page');
mjpage('$\\pi$ \\$', { singleDollars: true }, { html: true }, output => console.log(output))
```
gets:
```
        span = MathJax.HTML.Element("span", null, span);
               ^

ReferenceError: MathJax is not defined
    at tex2jax.startMatch (/mnt/c/Users/beep/git/c42lithium/node_modules/mathjax-node-page/lib/tex.js:240:16)
    at tex2jax.scanText (/mnt/c/Users/beep/git/c42lithium/node_modules/mathjax-node-page/lib/tex.js:172:32)
    at tex2jax.scanElement (/mnt/c/Users/beep/git/c42lithium/node_modules/mathjax-node-page/lib/tex.js:137:32)
    at tex2jax.scanElement (/mnt/c/Users/beep/git/c42lithium/node_modules/mathjax-node-page/lib/tex.js:149:22)
    at tex2jax.PreProcess (/mnt/c/Users/beep/git/c42lithium/node_modules/mathjax-node-page/lib/tex.js:66:14)
    at exports.mjpage (/mnt/c/Users/beep/git/c42lithium/node_modules/mathjax-node-page/lib/main.js:102:20)
    at Object.<anonymous> (/mnt/c/Users/beep/git/c42lithium/a.js:2:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by pkra** [comment]
> But currently in mathjax-node-page, if set { singleDollars: true }, there seems no way to handle the escaped dollar, and if there is any \$ in the text, an error is thown.

This matches the old `mj-page` behavior.

Try passing the `processEscapes` option in your configuration, e.g.,

```
{ 
  singleDollars: true,
  MathJax: {
    tex2jax: {
      processEscapes: true
    }
  }
}
```

**Comment by beeplin** [comment]
I have tried to pass the `processEsacpes` config into either `mj-page` or `mj-node` but the error remains. Seems the config is effective, but when generating `<span>$<span>` in `tex.js`, the object `Mathjax` is simply missing. see the error message above.

**Comment by pkra** [comment]
D'oh! Sorry for not reading carefully last night.  Silly bug.

**Comment by beeplin** [comment]
:)
